name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: sudo apt-get install -y build-essential ffmpeg wget

    - name: Create Tests Directory
      run: mkdir -p tests  # Create the tests directory if it doesn't exist

    - name: Download Sample Video
      run: wget -O rickroll.mp4 'http://www.youtube.com/get_video?video_id=eBGIQ7ZuuiU&l=210&sk=QHSGy-6-eiJ6h5qtrj1kR2OJanvL6tLlC&fmt_map=&t=OEgsToPDskIjlCX_1shTRBRDv2UQzVb-&hl=en&plid=AAROOIUyvpMFnjvzAAAAoARsYAg&tk=6J3d54cPnMJP7mUN2BtMkd2OmbgxTvB_GPcrV3ckGUbzd7KVMiH1kA%3D%3D&title=Rick Roll'

    - name: Build
      run: |
        g++ -o davinci-convert src/main.cpp -lstdc++fs

    - name: Run
      run: |
        echo "Running the Video Converter..."
        ./davinci-convert tests/sample_video.mp4 --output tests/output/video.mov
