name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: sudo apt-get install -y build-essential ffmpeg wget

    - name: Create Tests Directory
      run: mkdir -p tests  # Create the tests directory if it doesn't exist

    - name: Download Sample Video
      run: wget -O tests/sample_video.mp4 https://www.pexels.com/video/3195394/download/

    - name: Build
      run: |
        g++ -o davinci-convert src/main.cpp -lstdc++fs

    - name: Run
      run: |
        echo "Running the Video Converter..."
        ./davinci-convert tests/sample_video.mp4 --output tests/output/video.mov
